name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:latest
    steps:
      - uses: actions/checkout@v4

      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          repository: libsdl-org/SDL
          path: SDL

      - name: Install build tools
        run: |
          apk add build-base git bash cmake

      - name: Install ps2_drivers lib
        run: |
          git clone https://github.com/fjtrujy/ps2_drivers.git
          cd ps2_drivers
          make -j $(getconf _NPROCESSORS_ONLN) clean
          make -j $(getconf _NPROCESSORS_ONLN)
          make -j $(getconf _NPROCESSORS_ONLN) install

      - name: Compile SDL
        working-directory: SDL
        run: |
          cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$PS2DEV/ps2sdk/ps2dev.cmake
          cmake --build build
          cmake --install build

      - name: Compile Example
        run: |
          make

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ps2sdk-supertux
          path: supertux.elf
    
    
